import type { CityId, RegionLabel } from "@/types/atlas";

export type LabelOffset = { dx: number; dy: number };

export const LABEL_OFFSETS: Record<CityId, LabelOffset> = {
  antioch_pis:  { dx: -42, dy: -4 },
  iconium:      { dx: 0,   dy: -22 },
  lystra:       { dx: -8,  dy: 18 },
  derbe:        { dx: 36,  dy: 10 },
  tarsus:       { dx: 22,  dy: 18 },
  antioch_syr:  { dx: 30,  dy: -8 },
  seleucia:     { dx: -30, dy: 14 },
  salamis:      { dx: 20,  dy: 14 },
  paphos:       { dx: -22, dy: 14 },
  perga:        { dx: -18, dy: 16 },
  miletus:      { dx: -20, dy: 14 },
  ephesus:      { dx: 24,  dy: -4 },
  troas:        { dx: 0,   dy: -20 },
  philippi:     { dx: 0,   dy: -20 },
  thessalonica: { dx: -42, dy: -4 },
  berea:        { dx: -30, dy: 14 },
  athens:       { dx: 22,  dy: 14 },
  corinth:      { dx: -30, dy: 4 },
  caesarea:     { dx: -34, dy: 4 },
  tyre:         { dx: 26,  dy: 4 },
  ptolemais:    { dx: -34, dy: 4 },
  attalia:      { dx: 26,  dy: 14 },
  neapolis:     { dx: 30,  dy: 8 },
  cenchreae:    { dx: 30,  dy: 10 },
  sidon:        { dx: 24,  dy: -6 },
  myra:         { dx: 0,   dy: 18 },
  fair_havens:  { dx: 0,   dy: 20 },
  syracuse:     { dx: -32, dy: 4 },
  rhegium:      { dx: 26,  dy: 4 },
  jerusalem:    { dx: 0,   dy: 22 },
  damascus:     { dx: 26,  dy: -4 },
  malta:        { dx: 0,   dy: 22 },
  puteoli:      { dx: -26, dy: 14 },
  rome:         { dx: -24, dy: -8 },
};

export const REGION_LABELS: RegionLabel[] = [
  { lon: 20,   lat: 34.5, ru: "MARE · INTERNVM",    size: 30, letterSpacing: 20, opacity: 0.28, tier: "sea" },
  { lon: 25.5, lat: 39.3, ru: "MARE · AEGAEVM",     size: 14, letterSpacing: 6,  opacity: 0.4,  tier: "sea" },
  { lon: 31,   lat: 33.5, ru: "MARE · PHOENICIVM",  size: 11, letterSpacing: 4,  opacity: 0.4,  tier: "sea" },
  { lon: 17.5, lat: 41.5, ru: "MARE · ADRIATICVM",  size: 11, letterSpacing: 4,  opacity: 0.4,  tier: "sea" },
  { lon: 18,   lat: 38,   ru: "MARE · IONIVM",      size: 11, letterSpacing: 4,  opacity: 0.4,  tier: "sea" },

  { lon: 13.5, lat: 42,   ru: "ITALIA",             size: 22, letterSpacing: 8, tier: "prov" },
  { lon: 19,   lat: 41.8, ru: "ILLYRICVM",          size: 13, letterSpacing: 4, tier: "prov" },
  { lon: 21,   lat: 42.8, ru: "MOESIA",             size: 12, letterSpacing: 4, tier: "prov" },
  { lon: 27,   lat: 42,   ru: "THRACIA",            size: 13, letterSpacing: 4, tier: "prov" },

  { lon: 22.5, lat: 40.6, ru: "MACEDONIA",          size: 16, letterSpacing: 5, tier: "prov" },
  { lon: 23,   lat: 38,   ru: "ACHAIA",             size: 16, letterSpacing: 5, tier: "prov" },
  { lon: 20.5, lat: 39.5, ru: "EPIRVS",             size: 11, letterSpacing: 3, tier: "prov" },

  { lon: 29,   lat: 39.5, ru: "ASIA",               size: 15, letterSpacing: 5, tier: "prov" },
  { lon: 30.5, lat: 40.7, ru: "BITHYNIA",           size: 12, letterSpacing: 3, tier: "prov" },
  { lon: 35,   lat: 41.5, ru: "PONTVS",             size: 12, letterSpacing: 3, tier: "prov" },
  { lon: 33,   lat: 39.3, ru: "GALATIA",            size: 13, letterSpacing: 4, tier: "prov" },
  { lon: 30.5, lat: 38.3, ru: "PISIDIA",            size: 10, letterSpacing: 2, tier: "prov" },
  { lon: 30.5, lat: 37,   ru: "PAMPHYLIA",          size: 10, letterSpacing: 2, tier: "prov" },
  { lon: 29.5, lat: 36.6, ru: "LYCIA",              size: 10, letterSpacing: 2, tier: "prov" },
  { lon: 34,   lat: 36.8, ru: "CILICIA",            size: 11, letterSpacing: 3, tier: "prov" },
  { lon: 36,   lat: 38.7, ru: "CAPPADOCIA",         size: 12, letterSpacing: 3, tier: "prov" },
  { lon: 38,   lat: 39,   ru: "ARMENIA · MINOR",    size: 10, letterSpacing: 2, tier: "prov", opacity: 0.55 },
  { lon: 32,   lat: 38.3, ru: "LYCAONIA",           size: 9,  letterSpacing: 2, tier: "prov", opacity: 0.6 },
  { lon: 29.5, lat: 39.2, ru: "PHRYGIA",            size: 10, letterSpacing: 2, tier: "prov", opacity: 0.6 },
  { lon: 28,   lat: 40.3, ru: "MYSIA",              size: 9,  letterSpacing: 2, tier: "prov", opacity: 0.6 },

  { lon: 37,   lat: 34.8, ru: "SYRIA",              size: 16, letterSpacing: 5, tier: "prov" },
  { lon: 36,   lat: 32.8, ru: "DECAPOLIS",          size: 10, letterSpacing: 2, tier: "prov", opacity: 0.6 },
  { lon: 35.5, lat: 31.5, ru: "JUDAEA",             size: 14, letterSpacing: 4, tier: "prov" },
  { lon: 35.2, lat: 32.5, ru: "GALILAEA",           size: 10, letterSpacing: 2, tier: "prov", opacity: 0.7 },
  { lon: 35.7, lat: 32,   ru: "SAMARIA",            size: 10, letterSpacing: 2, tier: "prov", opacity: 0.65 },
  { lon: 35.5, lat: 33.5, ru: "PHOENICIA",          size: 11, letterSpacing: 3, tier: "prov" },
  { lon: 37.5, lat: 30.3, ru: "ARABIA",             size: 12, letterSpacing: 3, tier: "prov", opacity: 0.5 },
  { lon: 43,   lat: 34,   ru: "MESOPOTAMIA",        size: 14, letterSpacing: 4, tier: "prov", opacity: 0.55 },

  { lon: 31,   lat: 30.5, ru: "AEGYPTVS",           size: 18, letterSpacing: 5, tier: "prov" },
  { lon: 14,   lat: 31,   ru: "CYRENAICA",          size: 12, letterSpacing: 4, tier: "prov", opacity: 0.55 },

  { lon: 24.5, lat: 35.2, ru: "CRETA",              size: 11, letterSpacing: 3, tier: "island" },
  { lon: 33.3, lat: 35,   ru: "CYPRVS",             size: 11, letterSpacing: 3, tier: "island" },
  { lon: 14.5, lat: 37.6, ru: "SICILIA",            size: 12, letterSpacing: 3, tier: "island" },
  { lon: 14.5, lat: 35.9, ru: "MELITA",             size: 9,  letterSpacing: 2, tier: "island", opacity: 0.7 },
  { lon: 28,   lat: 36.4, ru: "RHODVS",             size: 9,  letterSpacing: 2, tier: "island", opacity: 0.7 },
];
